Adding Render pages
OvertureMIDI/Black-MIDI-Guides pull request #23
Opened 2024-02-05 13:59 UTC by PopoTheGamer

Adding Render pages, for introducing some Black MIDI rendering options.

2024-02-05 16:30 UTC, GreenWeegeeCantCode commented
this definitely wont be merged because this has some spelling errors, also UMP and zenith shouldnt be in one doc, they should be seperate guides and there shouldnt be just 1 guide with 2 rendering programs, before making a pr please check for any errors and if it contains multiple programs make them seperate guides.

2024-02-06 13:23 UTC, 6gh requested changes
Hey! Thanks for taking the time to submit a pull request with your suggestions! While this isn't in the format of the other guides, nor does it explain how to install and set up these programs, it did give me an idea to make a "Start" section for absolute complete beginners who don't even know where to start. I will probably use this to make a "Rendering MIDIs" page in there.

With this new idea in mind, I think your changes are great for what I explained above. Please use my comments to fix it up and I will do the rest in creating that new, "Start", section. Thank you again for contributing!

2024-02-06 13:23 UTC, 6gh commented on docs/Render/images/sample
> +nothing here
You should delete this file

2024-02-06 13:23 UTC, 6gh commented on docs/Render/index.md
> +# Renderring Black MIDI
Rendering*

2024-02-06 13:23 UTC, 6gh commented on docs/Render/index.md
> +Zenith has 2 versions which you can choose to start with:
Maybe explain a little of what the modded version does?

2024-02-06 13:23 UTC, 6gh commented on docs/Render/index.md
> +![Original Zenith Application when started](images/ZenithPreview.png)
I think we should move this right under the "# Zenith" header

2024-02-06 13:23 UTC, 6gh commented on docs/Render/index.md
> +![UMP playing a MIDI](images\UMPPreview.png)
Same thing with the Zenith image, maybe move this to right under the header

2024-02-06 13:32 UTC, 6gh commented
> this definitely wont be merged because this has some spelling errors, also UMP and zenith shouldnt be in one doc, they should be seperate guides and there shouldnt be just 1 guide with 2 rendering programs, before making a pr please check for any errors and if it contains multiple programs make them seperate guides.

You are not wrong, I would prefer for UMP and Zenith to have their own section. Although this PR did give me a new idea (explained a bit in the comment I left) so I can still probably use this PR.

In short, I'll make a new section called "Start" to have pages such as "How to make Black MIDI", "How to play Black MIDI", and "How to render Black MIDI" (this is where this PR comes in), where in these pages they then link to the actual guides on how to setup a variety of programs. This way newcomers who know nothing of the process can more quickly learn which programs do what and only read the pages they want to.

Let me know what you think of this idea, I'm open to suggestions as always!

> PS: Please try not to be so harsh on new contributors. Maybe it wasn't your intention, but your comment here and on the closed PR gives off a passive aggressive tone and overall not welcoming. It's partly my fault for procrastinating on finishing the Contributing guide for this project, which I will finish up when I get on a PC. Thank you for looking out for this project though!

2024-02-06 15:20 UTC, PopoTheGamer commented
Somehow I've included both Zenith and UMP into a single page because the page was meant to be an introduction to both of the programs and will let newcomers choose one out of it to start rendering their first Black MIDI video. That's why I didn't include the "how to install and set up" thing because I think it would be good to be done on separate pages.

2024-02-06 23:40 UTC, 6gh approved these changes
Looks good! I will make a "Start" section using this. Thank you for your contribution!

2024-02-06 23:42 UTC, merged